In [39]:
from langchain_google_genai import ChatGoogleGenerativeAI
import os
from dotenv import load_dotenv
from typing import TypedDict, List, Any
from pydantic import BaseModel, Field
# from huggingface_hub import InferenceClient
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage
from langchain_core.outputs import ChatResult, ChatGeneration
import numpy as np
import pandas as pd

In [40]:
application_train_exp = pd.read_csv("application_train_373139.csv")
bureau_balance_exp = pd.read_csv("bureau_balance_373139.csv")
bureau_exp = pd.read_csv("bureau_373139.csv")
credit_card_balance_exp = pd.read_csv("credit_card_balance_373139.csv")
installments_payments_exp = pd.read_csv("installments_payments_373139.csv")
POS_CASH_balance_exp = pd.read_csv("POS_CASH_balance_373139.csv")
previous_application_exp = pd.read_csv("previous_application_373139.csv")

In [41]:
final_dataset_exp = pd.read_csv("final_dataset_373139.csv")
final_dataset_exp

,AT_NAME_CONTRACT_TYPE,AT_CODE_GENDER,AT_FLAG_OWN_CAR,AT_FLAG_OWN_REALTY,AT_NAME_TYPE_SUITE,AT_NAME_INCOME_TYPE,AT_NAME_EDUCATION_TYPE,AT_NAME_FAMILY_STATUS,AT_NAME_HOUSING_TYPE,AT_OCCUPATION_TYPE,...,BB_STATUS_C_mean_mean,BB_STATUS_C_mean_max,BB_STATUS_Others_mean_mean,BB_STATUS_Others_mean_max,BB_STATUS_X_mean_mean,BB_STATUS_X_mean_max,BB_MONTHS_BALANCE_mean_mean,BB_MONTHS_BALANCE_mean_max,BB_MONTHS_BALANCE_max_mean,BB_MONTHS_BALANCE_max_max
0,0.0,1.0,1.0,1.0,6.0,6.0,4.0,3.0,1.0,0.0,...,0.46047,0.615385,0.0,0.0,0.066239,0.111111,-9.0,-2.5,0.0,0

In [42]:
table_definitions = {
    "application_train": [
        "Contains info about current loan and loan applicant at application time."
    ],
    "bureau": [
        "All client's previous credits provided by other financial institutions that were reported to Credit Bureau (for clients who have current loan).",
        "For every current loan, there are as many rows as number of credits the client had in Credit Bureau before the application date."
    ],
    "bureau_balance": [
        "Contains monthly balances of previous credits in Credit Bureau.",
        "Has one row for each month of history of every previous credit reported to Credit Bureau."
    ],
    "POS_CASH_balance": [
        "Contains monthly balance snapshots of previous POS (point of sales) and cash loans that the applicant had with Home Credit.",
        "Has one row for each month of history of every previous credit in Home Credit (consumer credit and cash loans) related to current loan."
    ],
    "credit_card_balance": [
        "Contains monthly balance snapshots of previous credit cards that the applicant has with Home Credit.",
        "Has one row for each month of history of every previous credit in Home Credit (consumer credit and cash loans) related to current loan."
    ],
    "previous_application": [
        "All previous applications for Home Credit loans of clients who have current loan.",
        "There is one row for each previous application related to current loan."
    ],
    "installments_payments": [
        "Repayment history for the previously disbursed credits in Home Credit related to current loan.",
        "There is a) one row for every payment that was made plus b) one row each for missed payment.",
        "One row is equivalent to one payment of one installment OR one installment corresponding to one payment of one previous Home Credit credit related to current loan."
    ] 
}

In [43]:
global_feature_importance = ['AT_EXT_SOURCE_2', 'AT_EXT_SOURCE_3', 'AT_DAYS_EMPLOYED',
       'AT_AMT_GOODS_PRICE', 'AT_AMT_CREDIT', 'AT_CODE_GENDER',
       'AT_DAYS_BIRTH', 'B_DAYS_CREDIT_max', 'AT_DAYS_ID_PUBLISH',
       'AT_AMT_ANNUITY', 'PC_CNT_INSTALMENT_FUTURE_mean_mean',
       'AT_NAME_EDUCATION_TYPE', 'PC_CNT_INSTALMENT_FUTURE_mean_max',
       'IP_AMT_PAYMENT_mean_max', 'B_AMT_CREDIT_SUM_max',
       'PA_CNT_PAYMENT_mean', 'PA_HOUR_APPR_PROCESS_START_mean',
       'IP_AMT_PAYMENT_mean_mean', 'AT_DAYS_REGISTRATION',
       'B_AMT_CREDIT_SUM_DEBT_max', 'AT_TOTALAREA_MODE',
       'PA_SELLERPLACE_AREA_mean', 'B_CREDIT_TYPE_Mortgage_mean',
       'PA_NAME_CLIENT_TYPE_New_mean', 'PC_SK_DPD_DEF_max_mean']

final_dataset_exp[global_feature_importance]

,AT_EXT_SOURCE_2,AT_EXT_SOURCE_3,AT_DAYS_EMPLOYED,AT_AMT_GOODS_PRICE,AT_AMT_CREDIT,AT_CODE_GENDER,AT_DAYS_BIRTH,B_DAYS_CREDIT_max,AT_DAYS_ID_PUBLISH,AT_AMT_ANNUITY,...,PA_CNT_PAYMENT_mean,PA_HOUR_APPR_PROCESS_START_mean,IP_AMT_PAYMENT_mean_mean,AT_DAYS_REGISTRATION,B_AMT_CREDIT_SUM_DEBT_max,AT_TOTALAREA_MODE,PA_SELLERPLACE_AREA_mean,B_CREDIT_TYPE_Mortgage_mean,PA_NAME_CLIENT_TYPE_New_mean,PC_SK_DPD_DEF_max_mean
0,0.413758,NaN,-2129,360000.0,360000.0,1.0,-9312,-178,-1665,21883.5,...,9.333333,12.0,7733.084107,-8884.0,0.0,NaN,24.666667,0.0,0.333333,0.0

In [44]:
def create_feature_dict(features_name: List[str], df_map: dict) -> dict:
    dict_ = {
        'application_train': [],
        'bureau_balance': [],
        'bureau': [],
        'credit_card_balance': [],
        'installments_payments': [],
        'POS_CASH_balance': [],
        'previous_application': []
    }
    detailed_dict_ = {}

    for feature in features_name:
        prefix = feature.split("_")[0]
        remain = feature.split("_")[1:]
        filtered_remain = [x for x in remain if x.isupper() or x.isnumeric()]
        feature = "_".join(filtered_remain)

        if prefix == "AT":
            dict_['application_train'].append(feature)
        elif prefix == "B":
            dict_['bureau'].append(feature)
        elif prefix == "BB":
            dict_['bureau_balance'].append(feature)
        elif prefix == "CC":
            dict_['credit_card_balance'].append(feature)
        elif prefix == "IP":
            dict_['installments_payments'].append(feature)
        elif prefix == "PC":
            dict_['POS_CASH_balance'].append(feature)
        elif prefix == "PA":
            dict_['previous_application'].append(feature)

    dict_ = {k: list(dict.fromkeys(v)) for k, v in dict_.items() if len(v) > 0}

    for name, features in dict_.items():          # features is a list
        detailed_dict_[name] = {}
        df = df_map[name]
        
        for feature in features:                  # iterate over each column name
            # .values → numpy array, .tolist() → Python list
            detailed_dict_[name][feature] = df[feature].values.tolist()

    return detailed_dict_

In [57]:
df_map = {
    "application_train": application_train_exp,
    "bureau": bureau_exp,
    "bureau_balance": bureau_balance_exp,
    "credit_card_balance": credit_card_balance_exp,
    "installments_payments": installments_payments_exp,
    "POS_CASH_balance": POS_CASH_balance_exp,
    "previous_application": previous_application_exp,
}

detailed_dict_ = create_feature_dict(global_feature_importance, df_map)
detailed_dict_

{'application_train': {'EXT_SOURCE_2': [0.4137577624682256],
  'EXT_SOURCE_3': [nan],
  'DAYS_EMPLOYED': [-2129],
  'AMT_GOODS_PRICE': [360000.0],
  'AMT_CREDIT': [360000.0],
  'CODE_GENDER': ['M'],
  'DAYS_BIRTH': [-9312],
  'DAYS_ID_PUBLISH': [-1665],
  'AMT_ANNUITY': [21883.5],
  'NAME_EDUCATION_TYPE': ['Secondary / secondary special'],
  'DAYS_REGISTRATION': [-8884.0],
  'TOTALAREA_MODE': [nan]},
 'bureau': {'DAYS_CREDIT': [-178, -520, -761, -790],
  'AMT_CREDIT_SUM': [0.0, 61490.475, 19488.6, 39105.0],
  'AMT_CREDIT_SUM_DEBT': [0.0, 0.0, 0.0, 0.0],
  'CREDIT_TYPE': ['Credit card',
   'Consumer credit',
   'Consumer credit',
   'Consumer credit']},
 'installments_payments': {'AMT_PAYMENT': [3171.195,
   14536.71,
   3171.195,
   14534.505,
   3168.675,
   2063.61,
   2.52,
   2063.61,
   11580.93,
   2063.61,
   2063.61,
   19236.87,
   14536.71,
   2063.61,
   14536.71,
   3171.195,
   3171.195]},
 'POS_CASH_balance': {'CNT_INSTALMENT_FUTURE': [11.0,
   1.0,
   3.0,
   12.0,
   0.0,
   4.0,
   2.0,
   3.0,
   2.0,
   4.0,
   0.0,
   5.0,
   6.0,
   9.0,
   0.0,
   9.0,
   7.0,
   1.0],
  'SK_DPD_DEF': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]},
 'previous_application': {'CNT_PAYMENT': [12.0, 12.0, 4.0],
  'HOUR_APPR_PROCESS_START': [14, 13, 9],
  'SELLERPLACE_AREA': [12, 32, 30],
  'NAME_CLIENT_TYPE': ['Repeater', 'New', 'Refreshed']}}

In [45]:
def create_feature_description(for_dict: dict, description_file_path: str) -> dict:
    description = pd.read_csv(description_file_path, encoding='latin1')
    desc_lookup = {}
    feature_descriptions = {}
    
    # Normalize table names if needed (optional but safer)
    table_name_map = {
        "application_train": "application_{train|test}",
        "bureau": "bureau",
        "bureau_balance": "bureau_balance",
        "credit_card_balance": "credit_card_balance",
        "installments_payments": "installments_payments",
        "POS_CASH_balance": "POS_CASH_balance",
        "previous_application": "previous_application",
    }
    
    for _, row in description.iterrows():
        table = row["Table"]
        feature = row["Row"]
        desc = row["Description"]
        special = row["Special"]
        desc_lookup[f"{table}_{feature}"] = f"{desc} (Special: {special})"
    
    for table, features in for_dict.items():
        feature_descriptions[table] = {}
        
        # Get the official table name used in the description file
        official_table = table_name_map.get(table)
        
        for feature, values in features.items():
            # Try exact match first
            desc = desc_lookup.get(f"{official_table}.csv_{feature}", 1)
            
            feature_descriptions[table][feature] = desc
    
    return feature_descriptions

In [14]:
feature_descriptions = create_feature_description(for_dict=detailed_dict_, description_file_path="/Users/thuyduc/Projects/AI/AI Sandbox/Services/CreditRiskAgent/data/raw/HomeCredit_columns_description.csv")
feature_descriptions

{'application_train': {'EXT_SOURCE_2': 'Normalized score from external data source (Special: normalized)',
  'EXT_SOURCE_3': 'Normalized score from external data source (Special: normalized)',
  'DAYS_EMPLOYED': 'How many days before the application the person started current employment (Special: time only relative to the application)',
  'AMT_GOODS_PRICE': 'For consumer loans it is the price of the goods for which the loan is given (Special: nan)',
  'AMT_CREDIT': 'Credit amount of the loan (Special: nan)',
  'CODE_GENDER': 'Gender of the client (Special: nan)',
  'DAYS_BIRTH': "Client's age in days at the time of application (Special: time only relative to the application)",
  'DAYS_ID_PUBLISH': 'How many days before the application did client change the identity document with which he applied for the loan (Special: time only relative to the application)',
  'AMT_ANNUITY': 'Loan annuity (Special: nan)',
  'NAME_EDUCATION_TYPE': 'Level of highest education the client achieved (Special: nan)',
  'DAYS_REGISTRATION': 'How many days before the application did client change his registration (Special: time only relative to the application)',
  'TOTALAREA_MODE': 'Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor (Special: normalized)'},
 'bureau': {'DAYS_CREDIT': 'How many days before current application did client apply for Credit Bureau credit (Special: time only relative to the application)',
  'AMT_CREDIT_SUM': 'Current credit amount for the Credit Bureau credit (Special: nan)',
  'AMT_CREDIT_SUM_DEBT': 'Current debt on Credit Bureau credit (Special: nan)',
  'CREDIT_TYPE': 'Type of Credit Bureau credit (Car, cash,...) (Special: nan)'},
 'installments_payments': {'AMT_PAYMENT': 'What the client actually paid on previous credit on this installment (Special: nan)',
  'AMT_INSTALMENT': 'What was the prescribed installment amount of previous credit on this installment (Special: nan)'},
 'POS_CASH_balance': {'CNT_INSTALMENT_FUTURE': 'Installments left to pay on the previous credit (Special: nan)',
  'SK_DPD_DEF': 'DPD during the month with tolerance (debts with low loan amounts are ignored) of the previous credit (Special: nan)'},
 'previous_application': {'CNT_PAYMENT': 'Term of previous credit at application of the previous application (Special: nan)',
  'HOUR_APPR_PROCESS_START': 'Approximately at what day hour did the client apply for the previous application (Special: rounded)',
  'SELLERPLACE_AREA': 'Selling area of seller place of the previous application (Special: nan)',
  'NAME_CLIENT_TYPE': 'Was the client old or new client when applying for the previous application (Special: nan)'}}

In [46]:
optimal_threshold_calibrated = 0.08644900452917655

output_from_ml_model_shap = {
    'baseline value': np.float64(0.0722),
    'probability for positive class': np.float64(0.0885),
    'late payment?': 'True',
    'top feature attribution': {
        'AT_CODE_GENDER': np.float64(0.0183),
        'AT_AMT_GOODS_PRICE': np.float64(0.0102),
        'B_CREDIT_ACTIVE_Closed_mean': np.float64(-0.0071),
        'B_AMT_CREDIT_SUM_DEBT_mean': np.float64(-0.0051),
        'AT_NAME_EDUCATION_TYPE': np.float64(0.0045),
        'AT_NAME_INCOME_TYPE': np.float64(0.0035),
        'IP_AMT_INSTALMENT_max_max': np.float64(-0.0026),
        'PA_PRODUCT_COMBINATION_Cash Street: middle_mean': np.float64(-0.0025),
        'PA_NAME_TYPE_SUITE_Unaccompanied_mean': np.float64(-0.0019),
        'PA_SELLERPLACE_AREA_max': np.float64(-0.0012)
    }
}

In [48]:
feature_attributions = output_from_ml_model_shap['top feature attribution'].keys()

detailed_dict_for_features_attributions = create_feature_dict(feature_attributions, df_map)
detailed_dict_for_features_attributions

{'application_train': {'CODE_GENDER': ['M'],
  'AMT_GOODS_PRICE': [360000.0],
  'NAME_EDUCATION_TYPE': ['Secondary / secondary special'],
  'NAME_INCOME_TYPE': ['Working']},
 'bureau': {'CREDIT_ACTIVE': ['Active', 'Closed', 'Closed', 'Closed'],
  'AMT_CREDIT_SUM_DEBT': [0.0, 0.0, 0.0, 0.0]},
 'installments_payments': {'AMT_INSTALMENT': [3171.195,
   14536.71,
   3171.195,
   14534.505,
   3171.195,
   2063.61,
   3171.195,
   2063.61,
   11580.93,
   2063.61,
   2063.61,
   19236.87,
   14536.71,
   2063.61,
   14536.71,
   3171.195,
   3171.195]},
 'previous_application': {'PRODUCT_COMBINATION': ['POS other with interest',
   'POS mobile with interest',
   'POS household with interest'],
  'NAME_TYPE_SUITE': ['Unaccompanied', 'Unaccompanied', 'Family'],
  'SELLERPLACE_AREA': [12, 32, 30]}}

In [111]:
class AgentState(TypedDict):
    customer_infomation: dict     # Thông tin khách hàng
    prob_positive: float          # Xác suất dự đoán của nhãn Positive
    baseline_value: float         # Giá trị baseline từ SHAP
    late_payment: str             # Có thanh toán trễ hay không (Boolean)
    top_feature_contribution: dict# Đóng góp của các đặc trưng quan trọng nhất (theo SHAP) vào xác suất dự đoán
    
    customer_summary: str         # Một bản tóm tắt thông tin khách hàng
    customer_credit_risk_explaination: str # Một bản báo cảo xác xuất khách hàng trễ hạn thanh toán trong đơn vay hiện tại, kèm theo lời giải thích

In [ ]:
from langchain_core.messages import SystemMessage, HumanMessage
class CreditRiskAgent:
    def __init__(self, llm: ChatGoogleGenerativeAI):
        self.llm = llm

    def create_feature_description(self, for_dict:dict, description_file_path:str) -> dict:
        description = pd.read_csv(description_file_path, encoding='latin1')
        desc_lookup = {}
        feature_descriptions = {}
        
        # Normalize table names if needed (optional but safer)
        table_name_map = {
            "application_train": "application_{train|test}",
            "bureau": "bureau",
            "bureau_balance": "bureau_balance",
            "credit_card_balance": "credit_card_balance",
            "installments_payments": "installments_payments",
            "POS_CASH_balance": "POS_CASH_balance",
            "previous_application": "previous_application",
        }
        
        for _, row in description.iterrows():
            table = row["Table"]
            feature = row["Row"]
            desc = row["Description"]
            special = row["Special"]
            desc_lookup[f"{table}_{feature}"] = f"{desc} (Special: {special})"
        
        for table, features in for_dict.items():
            feature_descriptions[table] = {}
            
            # Get the official table name used in the description file
            official_table = table_name_map.get(table)
            
            for feature, values in features.items():
                # Try exact match first
                desc = desc_lookup.get(f"{official_table}.csv_{feature}", 1)
                
                feature_descriptions[table][feature] = desc
        
        return feature_descriptions
    
    def get_table_definitions(self, detailed_dict:dict):
        selected_tables = detailed_dict.keys()
        table_definitions_text = "\n".join(
            f"- {table_name}:\n" +
            "\n".join(f"    - {definition}" for definition in table_definitions[table_name])
            for table_name in selected_tables
        )

        return table_definitions_text
    
    def customer_summarize_node(self, state: AgentState):
        """
        Tạo ra một bản tóm tắt hồ sơ khách hàng, về các lịch sử giao dịch trong quá khứ, hành vi khách hàng, lý lịch của khách hàng,...
        """
        print("--- Creating customer summarisation report ---")
        customer_info = state["customer_infomation"] # output a dictionary

        table_definitions_text = self.get_table_definitions(customer_info)

        feature_descriptions = self.create_feature_description(for_dict=customer_info, description_file_path="/Users/thuyduc/Projects/AI/AI Sandbox/Services/CreditRiskAgent/data/raw/HomeCredit_columns_description.csv")
        
        sys_message = SystemMessage(
            content=f"""
            You are a professional Credit Risk Analyst Agent.

            Your task is to carefully read the customer's data (provided by user) and generate a clear, structured, and insightful summary of the customer.

            ### Input Data Structure
            You will receive a dictionary with the following format:
            {{
                "table_name": {{
                    "feature_name": [value1, value2, ...],
                    ...
                }},
                ...
            }}

            - Some features contain a single value (from `application_train`).
            - Other features contain a list of values (from related tables like `bureau`, `installments_payments`, `POS_CASH_balance`, etc.).

            ### Table Definitions
            {table_definitions_text}

            ### Feature Definitions
            {feature_descriptions}

            ### Instructions
            1. Analyze every feature in given dictionary.
            2. Use the table and feature definitions to correctly interpret the meaning of each value.
            3. Pay special attention to:
            - Missing values (NaN)
            - Negative values (especially days-related features → they represent days before application)
            - Multiple values in related tables (summarize patterns, averages, extremes, trends)
            4. Write a professional and comprehensive customer summary that covers all useful insights. Structure the summary into the following sections (use these exact headings):
                **1. Demographic & Personal Profile**
                - Age, gender, education level, and other personal characteristics.
                - Housing / registration related information (if available).

                **2. Employment & Income Situation**
                - Current employment duration and stability.
                - Any available income or annuity information.

                **3. Current Loan Application**
                - Loan amount, goods price, annuity, and other key application details.
                - External credit scores (EXT_SOURCE) if available.

                **4. Credit History Overview**
                - Number and types of previous credits (from bureau / previous applications).
                - Credit amounts, outstanding debt, and credit types.
                - How recent the previous credits are.

                **5. Payment Behavior & History**
                - Payment patterns from installments (whether the customer paid the full installment amount, underpaid, or overpaid).
                - Frequency and consistency of payments.
                - Any signs of late payments or difficulties (if available from DPD or similar features).

                **6. Ongoing Credit Obligations**
                - Remaining installments (CNT_INSTALMENT_FUTURE).
                - Current status of previous POS / cash loans or other active products.

                **7. Overall Behavioral Insights & Risk Signals**
                - Summarize the customer's overall credit behavior (responsible / risky / mixed).
                - Highlight any positive signals (good payment history, stable employment, etc.).
                - Highlight any concerning signals (high debt, missing data, irregular payments, short credit history, etc.).
                - Do NOT give a final approve/reject decision — only describe observations.

            ### Output Format
            Write in clear, professional English. Be specific and use numbers from the data whenever possible. Do not include any extra explanation or markdown code blocks.
            """
        )

        human_message = HumanMessage(
            content=f"""Here is the customer's detailed data: 
            {customer_info}
            Please generate a professional summary of this customer.""")
        
        messages = [
            sys_message,
            human_message
        ]
        
        result = self.llm.invoke(messages)
        
        return {"customer_summary": result.content}

    def create_feature_dict(self, features_name: List[str], df_map: dict) -> dict:
        dict_ = {
            'application_train': [],
            'bureau_balance': [],
            'bureau': [],
            'credit_card_balance': [],
            'installments_payments': [],
            'POS_CASH_balance': [],
            'previous_application': []
        }
        detailed_dict_ = {}

        for feature in features_name:
            prefix = feature.split("_")[0]
            remain = feature.split("_")[1:]
            filtered_remain = [x for x in remain if x.isupper() or x.isnumeric()]
            feature = "_".join(filtered_remain)

            if prefix == "AT":
                dict_['application_train'].append(feature)
            elif prefix == "B":
                dict_['bureau'].append(feature)
            elif prefix == "BB":
                dict_['bureau_balance'].append(feature)
            elif prefix == "CC":
                dict_['credit_card_balance'].append(feature)
            elif prefix == "IP":
                dict_['installments_payments'].append(feature)
            elif prefix == "PC":
                dict_['POS_CASH_balance'].append(feature)
            elif prefix == "PA":
                dict_['previous_application'].append(feature)

        dict_ = {k: list(dict.fromkeys(v)) for k, v in dict_.items() if len(v) > 0}

        for name, features in dict_.items():          # features is a list
            detailed_dict_[name] = {}
            df = df_map[name]
            
            for feature in features:                  # iterate over each column name
                # .values → numpy array, .tolist() → Python list
                detailed_dict_[name][feature] = df[feature].values.tolist()

        return detailed_dict_
    
    def customer_credit_risk_explaination_node(self, state: AgentState):
        """
        Tạo ra một bản báo cáo xác xuất khách hàng trễ hạn thanh toán trong đơn vay hiện tại từ mô hình ML, kèm theo lời giải thích tại sao khách hàng có xác suất trễ hạn thanh toán cao hoặc thấp, dựa trên các đặc trưng quan trọng nhất (theo SHAP).
        """
        print("--- Creating customer credit risk explaination report ---")
        df_name_map = {
            "AT": "application_train",
            "B": "bureau",
            "BB": "bureau_balance",
            "CC": "credit_card_balance",
            "IP": "installments_payments",
            "PC": "POS_CASH_balance",
            "PA": "previous_application",
        }
        
        prob_positive = state["prob_positive"]
        baseline_value = state["baseline_value"]
        late_payment = state["late_payment"]
        top_feature_contribution = state["top_feature_contribution"]
        
        dict_ = self.create_feature_dict(list(top_feature_contribution.keys()), df_map)
        
        final_dict = {
            table: {
                feature: {
                    "value": values
                }
                for feature, values in features.items()
            }
            for table, features in dict_.items()
        }

        for key, value in top_feature_contribution.items():
            prefix = key.split("_")[0]
            remain = key.split("_")[1:]
            filtered_remain = [x for x in remain if x.isupper() or x.isnumeric()]
            table_name = df_name_map.get(prefix)
            feature_name = "_".join(filtered_remain)
            final_dict[table_name][feature_name]["contribution"] = float(value)

        table_definitions_text = self.get_table_definitions(final_dict)
        
        feature_descriptions = self.create_feature_description(for_dict=final_dict, description_file_path="/Users/thuyduc/Projects/AI/AI Sandbox/Services/CreditRiskAgent/data/raw/HomeCredit_columns_description.csv")
        
        sys_message = SystemMessage(
            content=f"""
            You are a professional Credit Risk Analyst Agent specialized in explaining late payment risk predictions.
            Your task is to generate a clear, professional, and easy-to-understand report about the late payment risk of a specific customer, based on the machine learning model prediction and SHAP explanations.
            ### Available Information
            - **prob_positive**: The Machine Learning model's predicted probability that this customer will have a late payment on the current loan (value between 0 and 1).
            - **baseline_value**: The average predicted probability across all customers (SHAP baseline). This is the starting point before considering this customer's specific features.
            - **late_payment**: Boolean indicating whether the Machine Learning model predicts this customer will have a late payment (`True`) or not (`False`).
            - **final_dict**: Dictionary containing the top features that most influence the prediction.
                Structure:
                {{
                    "table_name": {{
                        "feature_name": {{
                            "value": [actual value(s) of the customer],
                            "contribution": shap_value  # positive = increases risk, negative = decreases risk
                        }},
                        ...
                    }},
                    ...
                }}
            - **feature_descriptions**: Definitions of the features.
            - **table_definitions**: Description of each data table.
            ### Instructions for the Report
            Write a professional report with the following structure (use these exact section headings):

            **1. Late Payment Risk Prediction**
            - Clearly state the predicted probability (`prob_positive`) as a percentage.
            - State whether the Machine Learning model predicts the customer will have a late payment or not (`late_payment`).
            - Compare the customer's probability with the baseline (`baseline_value`).  
            Example: "The customer's risk is X% higher/lower than the average customer."

            **2. Key Drivers of the Prediction**
            - Explain the most important features from `final_dict` that push the prediction up or down from the baseline.
            - For each important feature:
            - Mention the actual value of the customer.
            - Explain what the feature means (use `feature_descriptions`).
            - State whether its contribution **increases** or **decreases** the late payment risk.
            - Quantify the impact when useful (e.g., "This feature increases the risk by approximately 0.018").
            - Group the explanation by positive contributors (increase risk) and negative contributors (decrease risk) if it improves clarity.
            - Focus on the top features that have the largest absolute contribution.

            **3. Overall Risk Assessment**
            - Summarize the main reasons why this customer has higher or lower risk than average.
            - Highlight any notable patterns (e.g., education level, income type, credit history status, loan amount, etc.).
            - Keep the tone professional, objective, and neutral. Do **not** give a final approve/reject recommendation.

            ### Important Rules
            - Always use the actual numbers from `prob_positive`, `baseline_value`, and the `contribution` values.
            - Explain in clear business language (avoid pure technical jargon).
            - When a feature has multiple values (e.g. from bureau), summarize the pattern instead of listing every single value.
            - Do not invent information that is not provided.
            - Return **only** the report using the exact section headings above.  
            Do not add any introductory sentence, conclusion outside the structure, or markdown code blocks.
            """
        )
        
        human_message = HumanMessage(
            content=f"""
            Here is the information for this customer:

            - Predicted probability of late payment (prob_positive): {prob_positive}
            - Baseline probability (baseline_value): {baseline_value}
            - Machine Learning Model prediction (late_payment): {late_payment}

            Top contributing features (final_dict):
            {final_dict}

            Feature definitions:
            {feature_descriptions}

            Table definitions:
            {table_definitions_text}

            Please generate the late payment risk report.
        """
        )

        messages = [
            sys_message,
            human_message
        ]
        result = self.llm.invoke(messages)
        
        return {'customer_credit_risk_explaination': result.content}

In [126]:
from dotenv import load_dotenv
import os

load_dotenv(override=True)  # Load environment variables from .env file
GEMINI_API = os.getenv('GEMINI_API')
class GeminiModel:
    def __init__(self, api_key: str, model_name: str = "gemini-3-flash-preview"):
        self.api_key = api_key
        self.model_name = model_name
    
    def init_gemini_model(self):
        gemini = ChatGoogleGenerativeAI(
            model=self.model_name,
            max_output_tokens=50000,
            temperature=1.0,
            top_p=0.8,
            google_api_key=self.api_key # Use your actual API key here
        )
        return gemini

In [127]:
gemini_llm = GeminiModel(GEMINI_API, model_name="gemini-3-flash-preview").init_gemini_model()
credit_risk_agent = CreditRiskAgent(gemini_llm)

In [128]:
from langgraph.graph import StateGraph, START, END

workflow = StateGraph(AgentState)

workflow.add_node("customer_summarisation_node", credit_risk_agent.customer_credit_risk_explaination_node)
workflow.add_edge(START, "customer_summarisation_node")
workflow.add_edge("customer_summarisation_node", END)

app = workflow.compile()

In [129]:
initial_state = {
    "customer_infomation": detailed_dict_,
    "prob_positive": output_from_ml_model_shap['probability for positive class'],
    "baseline_value": output_from_ml_model_shap['baseline value'],
    "late_payment": output_from_ml_model_shap['late payment?'],
    "top_feature_contribution": output_from_ml_model_shap['top feature attribution']
}
result, feature_descriptions = app.invoke(initial_state)

--- Creating customer credit risk explaination report ---

InvalidUpdateError: Expected dict, got ({'customer_credit_risk_explaination': [{'type': 'text', 'text': '**1. Late Payment Risk Prediction**\n- The predicted probability of a late payment for this customer is 8.85%.\n- The Machine Learning model predicts that this customer will have a late payment on the current loan.\n- The customer\'s risk is 1.63% higher than the average customer baseline, which stands at 7.22%.\n\n**2. Key Drivers of the Prediction**\n\n**Factors Increasing Late Payment Risk:**\n- **Gender (CODE_GENDER):** The client is male. This demographic factor is the strongest driver in this profile, increasing the predicted risk by approximately 0.0183.\n- **Goods Price (AMT_GOODS_PRICE):** The price of the goods for which the loan is given is 360,000.00. This specific loan amount for the consumer goods increases the risk by 0.0102.\n- **Education Level (NAME_EDUCATION_TYPE):** The customer has a "Secondary / secondary special" education level. This contributes to an increase in risk of 0.0045.\n- **Income Type (NAME_INCOME_TYPE):** The customer’s income type is categorized as "Working," which increases the risk by 0.0035.\n\n**Factors Decreasing Late Payment Risk:**\n- **Credit Bureau Status (CREDIT_ACTIVE):** The customer has a history of both "Active" and "Closed" credits reported to the Credit Bureau. This historical activity decreases the risk by 0.0071.\n- **Current Debt (AMT_CREDIT_SUM_DEBT):** Across all credits reported to the Credit Bureau, the customer currently has 0.00 in debt. This lack of outstanding external debt decreases the risk by 0.0051.\n- **Previous Installment History (AMT_INSTALMENT):** The history of prescribed installment amounts on previous Home Credit loans (ranging from approximately 2,063 to 19,236) indicates a repayment track record that reduces risk by 0.0026.\n- **Previous Application Details (PRODUCT_COMBINATION):** The types of products previously applied for (specifically various Point of Sale interest-bearing loans) decrease the risk by 0.0025.\n- **Application Context (NAME_TYPE_SUITE & SELLERPLACE_AREA):** Whether the client was unaccompanied or with family during previous applications, combined with the size of the selling areas where previous loans were initiated, collectively reduces the risk by approximately 0.0031.\n\n**3. Overall Risk Assessment**\nThe customer\'s risk profile is slightly elevated compared to the average, primarily driven by demographic factors (Gender and Income Type) and the specific price of the goods being financed. However, this risk is significantly tempered by a very clean credit bureau report showing zero current outstanding debt and a solid history of closed accounts. Additionally, the customer has a documented history of making installment payments on previous Home Credit applications. The transition from the baseline to the final 8.85% probability is a result of these demographic and loan-specific risks outweighing the positive influence of the customer\'s strong repayment and debt history.', 'extras': {'signature': 'EqQaCqEaAWkUfRPBR3zxL55VRgVjzXSBBzDWPeKr8mi5FABeZ+0dN77OrzHOmaRHB1PTvLL+ooAZmtao/LFB9NHCEn26myaxDn6SIKKI93FRheYOnNEZUny6cdfPsKYfeQwyCSPEfcqiQ9S51Jq5ds+Ug4zC5ZnqsRHH6S0XqjVJSDgzaoeo8k07ulFiVfFQNAok3RN2i1yP23UblXFc1isys3skgb4fpStLNfoIHxl7VQV4PAbhLR0kG1c2OleO6s6P23t9u67F1XdI6Zcs6Ahn1KN/dBaAvfPONLtJpq6GOSS++5xaAcI1BbYklI3QsUF4gkMiHrwF6EROZLu1avqFjPV0rEyE65/KInw0AuJIQCcJ1c7sA+TbnR6PQlDojfd950l/ce+QPEXjo8TCbqe3Y8y7ZZXRXEYdm8gpE4280RcsM8fKQerJe042aOuNYiVO+ELqp+KZ9GWXRa5OjxayWo8JvDAJEi4CYobnkGg6sQOsqGfThAv5TLZ6CanTCG//0vl8BJMIycTjFRJUrcRX52TakbpZHFG3a6A+fcPZzNV4ZyUyh+S/z+5a7NUOxFK1vuU0PQ4W7y0kMaCDuxxngf//WKXcf89vDCrfT33cTirEMyZVT02v3eKDPmIqITH/fAQdslKfGFEGCLJdGWWbIuwjVtHzPgMHcbS1JoM1hlAuSuXWy0PYOECKQ9QKY6Ddl5mdUJoCXFQZmkqoF7c3L8WGyVDEi4qdJuFpbbtm0RybHVPRPnW621FGxrCNqoUWSnwqlnAjLnR1IQ8IXsbdsXC/ilPa700tBzA1yRfpeOQ8oZxVSIQPuhxHRVcrTORq28TuJlz7XpVmkR4eTxVPz4dTo/O40G2gDPVx5JD9EpzYjIqhdupHhr9jZGE1TKjPIRN1puKhqzhqrKk1QNw491B7UsrKBLdHsK7A1gbh2+RHbC3SuYbcVBEgTPtpoHhR3tJr5Ep+Cv/DDEAeRL5kuSEFUlDXEB/+RyfHkRPcKT55iF+pXfM2DhIjUqefGUL7sh/7v34QjNWT30eHtpbCNKGLkfSs9SjsPukNYru+Q2yuXl2dQoxHJ4ZC1lp6Taro56PKzZg4iN4/MwVsz1ue87OXiC/etswZaVSYC92TRZ1T9IgpLo3hV4GXeyKV3qUlH61rcQ3v1UoK4/NCKMDjgMJQoL4LtDyqJZT8MAsqzHQmlpEGLG5FK11Vl2DO9ckfV+3dyLu6p58REGeSTwOvVALHZ4R+MTpiG3Ti0lT0+2H4Z2ahJLapZI3H/BuAgFF7OLGlUURODpDoIiIe5cMojWKwHFnYUHCuqNgmUkzZgQdNl34196V4knhVWuTIlaL2aY5/in9/3dSSOboK7RzPiqXzcFWn4B4ubJzjiyBi6ahvRhvjtzi6WSzTDHk0EosI8BLAetrck8grki3dQskEvy5Xk0D2jnV/RA39PNXKSi2LTwrEd6FCkKveSjz98Vb5p4pirdUH7A+oQgdKW/6FpajnES336UKKStpZgGdfRaREKtY7mo0XE2mF/klNWvEsMXm5sQ5RgpiKwvvuNF5djBYpz7Sbmiv9guLcPs3jeN5/wCc5/rTTQzYOOFx0syFzPTtCyQ2H2Uj7nplvtCqFWwTCH0tHdHOVSBXKD/rgrBmUSIsiTcMCC5cbscQqXiJcwAhNrPCG00TqjFNxJhynqRKxbr8QfOwrCdaFN9ZxzpfsMRRZT5UPdJMznvNG4zQZtxo6f76MbccWFB3/g8p6Uja/uh2pQpQX+ysRxKuJU8Zjbgv/OtSfGt52K/aBzJUSsaRWhf/gWjCBiW1DxkuGz3ZuvJwMGCSIvfjKncCF+OVwKh11I5ps4/Z8CPUCcqX8mxdAafDs2X6Gtvu/xIM5vSD921whbEmPYOhLPBAeuToB9VAfIsWOwdsbuI6/dhizjOD653LptNyQQRaVHwoylaLPlozzzy0LRCqcPKO7ro0CgUdE5cNQMj4+Yt95h0c0L9NVzAfcjmCF0BnccGRvJ7ebY2MfyjTHXPTwE3S7iL3bvcN43c1m72Kn9SSSh3hXhAqotAwu1+WNLXpLRUSNO7g2eThc2htUZP68tP/cjH11Z6HBTPBMHkSZ7ITp0Ul/YEw3D8s1IO2m++gXwHSQgcZGmM7eZzQ8ut4tiXp6B0NqWrPIhaVBdee4btjXobsbNvLOWiCkCwEKmgzUHLdLbn0AE1eF0Gaas/3K2uVz68Ysqohx4adOfbCODKzZJwJtMSMUQVjy7LZnTf41r6x/TPaisHO01gdaEatBsa3d4FnzX7VUYdzjZKlaXie++4xwFS1Eajf0K7xr9wCgOg/Es/DaIMogzD6ejRmXyOD9zcv6zZOIrdLqXzaxtzwn9cZktmg4aLDtt1nZ3V5Jf7UQTp6fY9X4PrdepwpzIrweETlBHm5GedsQyQzCZbk/LhVjCy0HPuM8Sb5SPCKQgdCf70Z2CIYwFqzFsa0OCv6R9QAIqRzSVLHGGK0ls+tTUjWwaTvuejuxJHKfvl9f0DL5AxI8R6Gkkk3EFxGUq9PihtuY+jNc9upD47JVbOzm4FxhG9ozZq4+hU+2tBxpE27MC0iFjyr/TALg1bEqt6vd6ojazD5Xm26YLEKdz5w+QnrBYRXea6wIwsQUR8+KnKsqaV+zNLDC0F9vwSFlt5CrRb3iztkpSwhLZrH6gA4Y1WRILaDbWJA0uSST/q9mvR0g6UZstXeEUxYToGCGcie0yv1y9mOiZiVY6xYSPac0liqmriM9TadPRkTHoHTQQ+lM9C88vsY3e3PrZPjsL/CrktB0tuA3Bc8CP1EYWAQT3RN4NplBHzf3J81uj9ssGMJ07CZySa9ewVvtzVu5jneiQ6SgTggMD5knAnIdcDgHmBbfgl5Bgl3FF9epRsI79+qZz/uQgtEdgB9zMYj7dz4rD4tLQeOEV4zi4q6kEGPbHcFyW3dax3sPikWEAe0smDH34x3b7/GqmDdhC0okBR5Go7oAXg/XkSX7DJKxrFuQA0Wgw1eg6SJ0q6m9g+gOXMermgQlMtF/f8/lMq3SNGrH8dw4MVUYveYcyrMTRQAcNepyZIRzJYEZ0r/BtA6cYhCBsKO4tFPh4WgdUsK5eimBEcH6PDXXZLSYJHsPl546TW/ouG+j00TkeCndUTipScco1FKzYGcXBjQHoRzCgDpypT14Ly5GKIrkGw0Id0sHiNXDlR5ZZNI/fm5N1Z6hmRhwO4cVTvS2evKlCEZCoVJDvYYiC6NrGQwZ0UGYCKLtkMdiq/dZNsYZAEPP/ABcoRzACuLbwExA5foutbEjQf4icFRWpI1oLz4CkHA+SKafn/m+VKoerRwkhVoutuXAa6G3A5Lo+6eppYg+aiG1O+f9QjxFKLmu8bfW1cmfy5C2Dwx7twzk8EBliQv7KVZlwTYMRIzHNCl1NGMAnsBY6OBV+VUr4IK5W5Wtf51aAU7dZ0BLlrQvSGOBhHZs9/y/7AHwORh1Cae2LYeRpfkcYyyb0RDnyo5QftHFkBsChnuNVTqzx24oScDcOZBSmXhdTvXVlohdtnGbudusZw5rQN0AEe7Xn3sBGHWZacHCEl//a3ydTRSKzYvoRLxzdFfs4ZypXzEluxkfUVfkHNhiFy25/d7Em19hvynh9Bt3mhowcv6eMtPaMXyaziBfBeQbbgSGjnJaCAEu+FHDHffQxNn8TAe3Bme2qy76OCZ8I7ZxjOKLgnECxepBIGBqdTTmzM8utigybGIDWFeo/+WWcVFfHEjIfUUqS3V3OHwoxSoyE6Ws/m1Y27+wRZWW7Ui+XkJtbFdl07hqWwGSbguOM+NzMgREK92nsaBUy8yetK80ILsYhqw6JrUJLDrbjeuPV0BYBWuQoV62E5Wy0O2DoR2/b3H7kWuTd0w52dewgNLK7S40D+VyMtCz/Z0ruP1uK2QH0PWOa0dBJ+k+7ykgg4+W1zZVcmOX7b3zmoaHuWKGct6SQJaRHFStNOlLTnK/lOkB07UWoV9weebJGFkrYAoZpsAq8r8cmsq+ccJndVYSQsvdRu2xyl06uNSOndKLSniVKdNUfP1GQEd+rJD9+CVetIsHY+ySsqHY50WJ3PWnEnf0wqvKVxN7q0R5+MGaABrtImNJJazDwfnlyiIHzIvW92IGhHZbszJq2Ph2+h8XOi8KIL0uG+0bfFReXOoirbjOzH3hMga/W/GSL1VcevH/NzVtkC/EJ/FRdlvTqEOxeL/CBDPTU91VppYM9M7hBJfAk6OnwM5ZceQgWaulrQRUYRzMWSz79xzR7XkhFuvRFYND8oNJPbgDJBf7SXo7lmFt0TV/Hr0JTzeUUhExLECf7przIJ8srINpqh82kQwFDxx64Czpci4Qj8xfIILom+END5o/zF/BtPwr+6SHYQ4OWZz3ek/AV/vXXv7lPJZA1PuwTQb0PLbdOhm5Lz19Wf0PxUtsBEoNg4AXUK4xfe2qXsmoE451KQl/EPwVbv0FmPoTVgZOwg=='}}]}, {'application_train': {'CODE_GENDER': 'Gender of the client (Special: nan)', 'AMT_GOODS_PRICE': 'For consumer loans it is the price of the goods for which the loan is given (Special: nan)', 'NAME_EDUCATION_TYPE': 'Level of highest education the client achieved (Special: nan)', 'NAME_INCOME_TYPE': 'Clients income type (businessman, working, maternity leave,\x85) (Special: nan)'}, 'bureau': {'CREDIT_ACTIVE': 'Status of the Credit Bureau (CB) reported credits (Special: nan)', 'AMT_CREDIT_SUM_DEBT': 'Current debt on Credit Bureau credit (Special: nan)'}, 'installments_payments': {'AMT_INSTALMENT': 'What was the prescribed installment amount of previous credit on this installment (Special: nan)'}, 'previous_application': {'PRODUCT_COMBINATION': 'Detailed product combination of the previous application (Special: nan)', 'NAME_TYPE_SUITE': 'Who accompanied client when applying for the previous application (Special: nan)', 'SELLERPLACE_AREA': 'Selling area of seller place of the previous application (Special: nan)'}})
For troubleshooting, visit: https://docs.langchain.com/oss/python/langgraph/errors/INVALID_GRAPH_NODE_RETURN_VALUE

In [124]:
print(result["customer_credit_risk_explaination"][0]['text'])

**1. Late Payment Risk Prediction**
- The predicted probability of a late payment for this customer is 8.85%.
- Based on this probability, the Machine Learning model predicts that the customer will have a late payment.
- The customer's risk is 1.63 percentage points higher than the baseline average of 7.22%.

**2. Key Drivers of the Prediction**

**Factors Increasing Late Payment Risk:**
- **Gender (CODE_GENDER):** The client is male ('M'), which is the strongest driver in this profile, increasing the late payment risk by approximately 0.0183.
- **Goods Price (AMT_GOODS_PRICE):** The price of the goods for which the loan is given is 360,000.0. This specific loan amount contributes to an increase in risk of 0.0102.
- **Education Level (NAME_EDUCATION_TYPE):** The client’s highest education level is "Secondary / secondary special," which increases the risk by 0.0045.
- **Income Type (NAME_INCOME_TYPE):** The client’s income type is categorized as "Working," which adds 0.0035 to the risk probability.

**Factors Decreasing Late Payment Risk:**
- **Credit Bureau Status (CREDIT_ACTIVE):** The client has a history of one "Active" and three "Closed" credit accounts. This history of successfully closing previous credits reduces the risk by 0.0071.
- **Current Debt (AMT_CREDIT_SUM_DEBT):** The client currently has zero debt reported across all credits in the Credit Bureau. This lack of outstanding debt decreases the risk by 0.0051.
- **Previous Installment History (AMT_INSTALMENT):** The prescribed installment amounts on previous Home Credit loans (ranging from approximately 2,063 to 19,236) suggest a repayment history that lowers the risk by 0.0026.
- **Previous Application Details (PRODUCT_COMBINATION):** The client’s history with specific product types (Point of Sale mobile, household, and other interest-bearing loans) decreases the risk by 0.0025.
- **Application Context (NAME_TYPE_SUITE & SELLERPLACE_AREA):** Whether the client was unaccompanied or with family during previous applications, and the specific selling areas of those transactions, collectively reduce the risk by approximately 0.0031.

**3. Overall Risk Assessment**
The customer's predicted risk of 8.85% is moderately higher than the average customer baseline of 7.22%. The primary drivers for this increased risk are demographic and application-specific factors, notably the client's gender, education level (Secondary), and the specific price of the goods being financed.

However, the risk is significantly mitigated by a healthy credit history. The client shows a strong track record with the Credit Bureau, characterized by multiple closed accounts and, most importantly, zero current outstanding debt. Additionally, the client has experience with previous Home Credit installments and various product combinations, which are historically positive indicators. The model's prediction of a late payment appears to be driven more by the profile of the current application than by past financial behavior.

In [28]:
with open("workflow_graph.png", "wb") as f:
    f.write(app.get_graph().draw_mermaid_png())